server:
  port: 8084
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/springcloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/